### ISSUE TITLE
can this be used to grab purchases of the user?

### ISSUE THREAD

**Issue by sandrodz** [jacobbednarz/envato-ruby-sdk#11]
Hi,

I want to integrate this with discourse so I can provide support via discourse forum. Do you think I can use this to allow users posting in specific forums only if they have purchased item and are eligible for support?

You seem to know more than me about their API. So if you don't mind sharing info :)

**Comment by jacobbednarz** [comment]
Apologies for the delay in responding - For some reason I didn't get a notification about the new issue until I manually just popped in here.

> Do you think I can use this to allow users posting in specific forums only if they have purchased item and are eligible for support?

Definitely. I don't have a helper method for it just yet but there is nothing stopping you from doing something like this:

```
client = Envato::Client.new(access_token: 'mytops3crettoken')
response = client.get "v3/market/buyer/purchase?code=#{purchase_code}"
# response will contain the purchase information
```

> You seem to know more than me about their API. 

Funny that - I work in Envato's SRE team :wink:
